server:
  port: 9999
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.119.27:3306/code006?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 2019_Test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    thymeleaf:
      cache: false
  data:
    elasticsearch:
      cluster-nodes: 47.98.119.27:9300